### ISSUE TITLE
Firebase real time cloud function not working.

### ISSUE THREAD

**Issue by Mahato12nikhil** [fobo66/algolia-firebase-functions#149]
I have exactly did what you did but I am getting following issue.How to solve it?

C:\Users\NIKHIL MAHATO\Desktop\Algolia_Firebase\functions\index.js
  20:73  error  Parsing error: Unexpected token ;

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! algolia-firebase-functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the algolia-firebase-functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NIKHIL MAHATO\AppData\Roaming\npm-cache\_logs\2020-11-09T07_14_20_884Z-debug.log
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "%RESOURCE_DIR%" run lint ENOENT
    at notFoundError (C:\Users\NIKHIL MAHATO\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\NIKHIL MAHATO\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\NIKHIL MAHATO\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\NIKHIL MAHATO\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

Error: functions predeploy error: Command terminated with non-zero exit code1

**Comment by fobo66** [comment]
Hi! It looks like there's a lint issue in your code at `C:\Users\NIKHIL MAHATO\Desktop\Algolia_Firebase\functions\index.js`: semicolon at line 20
