### ISSUE TITLE
Function Deploy Error: Unexpected Token )

### ISSUE THREAD

**Issue by socceroos** [fobo66/algolia-firebase-functions#3]
The recent PR #2  seems to have introduced an issue when attempting to deploy functions. The polyfill is introducing the issue.

Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/algolia-firebase-functions/values-entries-polyfill.js:16
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/algolia-firebase-functions/index.js:16:29)

**Comment by fobo66** [comment]
Thanks for info! There were problems with [custom polyfills](https://github.com/tc39/proposal-object-values-entries) for Object.entries and Object.values, I've changed it to [es-shims](https://github.com/es-shims/es-shim-api) polyfills ([Object.values](github.com/es-shims/Object.values) and [Object.entries](github.com/es-shims/Object.entries)). Try to update your dependencies and redeploy functions.
