### ISSUE TITLE
exists function [breaking changes ]

### ISSUE THREAD

**Issue by invalidtruck** [fobo66/algolia-firebase-functions#6]
### Proposal
Change exists function to property 

### Why
The error :
```

TypeError: change.after.exists is not a function
    at Object.exports.syncAlgoliaWithFirebase (/user_code/node_modules/algolia-firebase-functions/index.js:73:21)
    at exports.syncAlgoliaWithFirebase.functions.firestore.document.onWrite (/user_code/index.js:15:26)
    at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
    at /var/tmp/worker/worker.js:768:24
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

I will make a pull request if necessary

**Comment by gautham20** [comment]
Facing the same issue

**Comment by invalidtruck** [comment]
> 
> 
> Facing the same issue
I did make a fork to be compatible with firestore
https://github.com/invalidtruck/algolia-firestore-functions

**Comment by fobo66** [comment]
Hello guys! Sorry for the late response, just got free time to invest in this project.

The issue you're talking about is not an actual bug, it's more of incompatibility between Firebase Database API and Firestore API.

I've created #37 to address this incompatibility.

**Comment by fobo66** [comment]
Since version 3.2.0 you will be able to use this library with Firestore.

Consider to use `syncAlgoliaWithFirestore` function.
